### PR TITLE
added two test vectors

### LINKED ISSUE #2: Test Vectors
# Description
Create an input file that will contain 5 test vectors for the benchmark circuit. This will be another main deliverable of project 0.

# Deliverable
- An input file named with the circuit name with _input with a .txt extension (ex. adder_input.txt)
- A text file with an explanation of the test vectors and why they are good test vectors named with the circuit name with _test_explanation with a .txt extension (ex. adder_test_explanation.txt)

### PR DESCRIPTION
**Pull request by mandapativishal**
closes #2

### CODE REVIEW

**Comment by ece-jacob-scott** [comment]
Any updates on this? Do you need any help?

**Comment by mandapativishal** [comment]
I will update the vector file by tonight

**Comment by ece-jacob-scott** [comment]
Do you have the explanations?

**Comment by mandapativishal** [comment]
Yeah should I post it here?

**Comment by ece-jacob-scott** [comment]
Yeah add it in a new file like the issue says. Thanks! Once you're done I'll finish and hand it in tomorrow.

**Comment by ece-jacob-scott** [comment]
Issue already closed by https://github.com/ece-jacob-scott/jscott35_ece464_p0/pull/8

**Pull request closed without merging**
